import Head from "next/head";

import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [companyDomains, setCompanyDomains] = useState([]);
  useEffect(() => {
    const dataFetch = async () => {
      const data = await (await fetch("http://localhost:3001/domains")).json();

      setCompanyDomains(data);
    };

    dataFetch();
  }, []);
  return (
    <>
      <Head>
        <title>Guess my corporate email</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;600&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>What is my company email?</h1>
        <h2 className={styles.description}>
          If we knew the company domain already, we will tell you the best email
          that you can give a try 🤓
        </h2>
        <form className={styles.form}>
          <input
            className={styles.inputText}
            placeholder="E.g.: Ada Lovelace"
          />

          <select className={styles.dropdownList}>
            <option>Please select one item</option>
            {companyDomains.map((domain) => {
              return <option>{domain}</option>;
            })}
          </select>
          <button type="submit" className={styles.primaryButton}>
            Search
          </button>
        </form>
        <section className={styles.result}>
          For this person, the email is probably:{" "}
        </section>
      </main>
      <footer className={styles.footer}>
        Made with 🧡 by:
        <a href="https://github.com/joseliacosta">joseliacosta</a>
      </footer>
    </>
  );
}
